services:
#  rabbitmq:
#    image: rabbitmq:3.12-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - microservices-network

  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      #      KEYCLOAK_USER: admin
      #      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - "8180:8080"
    networks:
        - backend
    depends_on:
        - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - backend

  identity-service:
    image: identity-service:latest
    ports:
      - "8085:8085"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - microservices-network

  email-service:
    image: email-service:latest
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - microservices-network

  amqp:
    image: amqp:latest
    ports:
      - "5672:5672"
    networks:
      - microservices-network

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-network

networks:

  backend:
    driver: bridge
  microservices-network:
    driver: bridge
